name: Run PyInstaDump

on:
  workflow_dispatch:       # lets you run manually from the Actions tab
  schedule:
    - cron: '0 2 * * *'    # optional: run daily at 02:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install || true

      - name: Run PyInstaDump
        env:
          COOKIES: ${{ secrets.COOKIES }}
        run: |
          mkdir -p data
          # Replace this username with whoever you want to scrape
          python -m pyinstadump.main \
            --username jimmy_on_relationships \
            --mode followers \
            --cookie "$COOKIES" \
            --output data/results.csv

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ig-results
          path: data/results.csv
