name: Run IG Scraper (run_scraper.py wrapper)

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies required by Playwright (non-fatal)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            ca-certificates libnss3 libatk-bridge2.0-0 libgtk-3-0 libxss1 \
            libasound2 libasound2-data libgbm1 libglib2.0-0 libx11-6 \
            libxcomposite1 libxcursor1 libxdamage1 libxrandr2 libxinerama1 \
            libpangocairo-1.0-0 libpango-1.0-0 libatk1.0-0 libcups2 libnspr4 \
            libxext6 libffi-dev libx264-dev ffmpeg wget unzip || true

      - name: Install Python packages & Playwright browsers
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install playwright requests aiohttp
          fi
          python -m playwright install --with-deps

      - name: Run wrapper script (writes cookies, diagnostics, runs scraper)
        env:
          COOKIES_SECRET: ${{ secrets.COOKIES_SECRET }}
        run: |
          mkdir -p data cookies
          python run_scraper.py

      - name: Show results preview + list data/
        run: |
          echo "=== data/ listing ==="
          ls -la data || true
          echo
          echo "=== results.csv preview (if exists) ==="
          if [ -f data/results.csv ]; then head -n 80 data/results.csv || true; else echo "No data/results.csv produced"; fi

      - name: Upload artifacts (results + debug HTML/PNG + cookie copies)
        uses: actions/upload-artifact@v4
        with:
          name: ig-scraper-artifacts
          path: |
            data/**
            debug_*.png
            debug_*.html
            www.instagram.com.cookies.json
            cookies/www.instagram.com.cookies.json
