name: Run Playwright IG profile scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.44.0
          pip install aiohttp
          pip install --quiet --upgrade pip
          python -m playwright install --with-deps

      - name: Run scraper
        env:
          COOKIES: ${{ secrets.COOKIES }}
        run: |
          python scrape_profiles.py

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ig-profile-results
          path: data/results.csv
