name: Run Instagram Follower Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    env:
      FOLLOWERS_LIMIT: '500'   # change to desired number (string)
      PROFILE_DELAY: '0.8'
      SCROLL_PAUSE: '0.6'
      HEADER_TIMEOUT_MS: '45000'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies (for Playwright / browsers)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            ca-certificates \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libxss1 \
            libasound2t64 \
            libasound2-data \
            libgbm1 \
            libglib2.0-0 \
            libx11-6 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxrandr2 \
            libxinerama1 \
            libpangocairo-1.0-0 \
            libpango-1.0-0 \
            libatk1.0-0 \
            libcups2 \
            libnspr4 \
            libxext6 \
            libffi-dev \
            libx264-dev \
            ffmpeg \
            wget \
            unzip || true

      - name: Install Python packages and Playwright browsers
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install playwright aiohttp; fi
          python -m playwright install --with-deps

      - name: Show debug info
        run: |
          echo "FOLLOWERS_LIMIT=${{ env.FOLLOWERS_LIMIT }}"
          echo "PROFILE_DELAY=${{ env.PROFILE_DELAY }}"
          echo "SCROLL_PAUSE=${{ env.SCROLL_PAUSE }}"
          echo "HEADER_TIMEOUT_MS=${{ env.HEADER_TIMEOUT_MS }}"
          echo "usernames.txt (first 20 lines):"
          sed -n '1,20p' usernames.txt || true

      - name: Run follower scraper
        env:
          COOKIES: ${{ secrets.COOKIES }}
          FOLLOWERS_LIMIT: ${{ env.FOLLOWERS_LIMIT }}
          PROFILE_DELAY: ${{ env.PROFILE_DELAY }}
          SCROLL_PAUSE: ${{ env.SCROLL_PAUSE }}
          HEADER_TIMEOUT_MS: ${{ env.HEADER_TIMEOUT_MS }}
        run: |
          mkdir -p data
          python scrape_followers.py || true
          echo "---- results.csv preview ----"
          head -n 40 data/results.csv || true
          echo "---- debug files in data/ ----"
          ls -la data || true

      - name: Upload all data files (results + debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ig-profile-results
          path: data/*
